version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: operadoras
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d operadoras"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi:secret@postgres:5432/operadoras
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./back/app:/app/app
      - ./Index.csv:/app/Index.csv

volumes:
  postgres_data: